name: featScratch

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "5 * * * *"
on: [workflow_dispatch]

jobs:
  featScratch:
    name: featScratch

    runs-on: macOS-latest

    steps:

      - name: init
        uses: actions/checkout@v1
      

      - name: clone
        env:
          sha: ${{steps.sha.outputs.value}} 
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone -b feature-scratch --depth 1 ${{secrets.GIT_ADDRESS1}} .
        shell: bash

      - name: get package
        id: package
        uses: Ireoo/get-package@v1
        with:
          path: package.json
          key: version
     
  tools:
    needs: [featScratch]

    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest, macOS-13, windows-latest]

    steps:
      - name: init
        uses: actions/checkout@master

      - name: set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: set python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8" 

      - name: clone
        env:
          sha: ${{steps.sha.outputs.value}} 
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone -b feature-scratch --depth 1 ${{secrets.GIT_ADDRESS1}} .
        shell: bash

      - name: install
        run: |
         npm i

#       - name: install electron-builder with macos latest
#         if: startsWith(matrix.os, 'macOS')
#         run: npm i electron-builder@21.2.0

      - name: win
        if: startsWith(matrix.os, 'windows')
        run: |
          npm run win
          npm run build
          
      - name: linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          npm run win
          npm run build
        
      - name: build:pure
        if: startsWith(matrix.os, 'macOS')
        run: npm run build:pure
        
      - name: mac:dmg
        if: startsWith(matrix.os, 'macOS')
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm run mac:dmg
        
      - name: mac:mas
        if: startsWith(matrix.os, 'macOS')
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm run mac:mas

      - name: get package version
        id: package
        uses: Ireoo/get-package@v1
        with:
          path: ./package.json
          key: version

      - name: get package productName
        id: package1
        uses: Ireoo/get-package@v1
        with:
          path: package.json
          key: productName

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: featAnimations_v${{steps.package.outputs.version}}
          name: featAnimations_v${{steps.package.outputs.version}}
          draft: false
          prerelease: true
          fail_on_unmatched_files: false
          append_body: true
          files: |
            build/*.exe
            build/*.msi
            build/latest.yml
            build/*.dmg
            build/*.zip
            build/*.AppImage
            build/*.pkg
            build/latest-mac.yml
            build/*.deb
            build/*.rpm
            build/*.apk
            build/latest-linux.yml
