name: Release

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"
# on: [push] 

jobs:
     
#   notools:
#     runs-on: ${{matrix.os}}
    
#     strategy:
#       fail-fast: false
#       matrix:
#         node: [12]
#         os: [ubuntu-latest, macos-latest, windows-latest]

#     steps:
#       - name: init
#         uses: actions/checkout@master

#       - name: set node
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node }}
          
#       - name: set python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.7'
#           architecture: 'x64'
      
#       - name: clone
#         env:
#           sha: ${{steps.sha.outputs.value}} 
#         run: |
#           ls -alF
#           rm -rf *
#           rm -rf .git
#           rm -rf .github
#           ls -alF
#           git clone ${{secrets.GIT_ADDRESS1}} .
#         shell: bash
      
#       - name: install
#         run: npm i
      
#       - name: install electron-builder with macos latest
#         if: startsWith(matrix.os, 'macOS')
#         run: npm i electron-builder@21.2.0
      
#       - name: build
#         run: npm run build:chromebook
      
#       - name: Upload to tools.integem.com
#         run: npm run upload noTools

  tools:
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        node: [14]
        os: [ubuntu-latest, macos-latest, windows-latest] # , macos-latest

    steps:
      - name: init
        uses: actions/checkout@master

      - name: set node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          
      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: clone
        env:
          sha: ${{steps.sha.outputs.value}} 
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone ${{secrets.GIT_ADDRESS1}} .
        shell: bash

      - name: install
        run: npm i

      - name: install electron-builder with macos latest
        if: startsWith(matrix.os, 'macOS')
        run: npm i electron-builder@21.2.0

      - name: win
        run: npm run win
        
      - name: build
        run: npm run build
        
      - name: Upload to tools.integem.com
        run: npm run upload

